#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gulimall-sms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#配置注册中心nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#当前应用的名字
  application:
    name: gulimall-coupon
#配置mybatis-plus
mybatis-plus:
  #配置读取的xml路径
  mapper-locations: classpath:/mapper/**/*.xml
  #配置主键自增
  global-config:
    db-config:
      id-type: auto
#端口
server:
  port: 7000
